force_keyboard_focus = true
selection_wrap = true
theme = "gruvbox"

[placeholders]
"default" = { input = "ï€‚ Search...", list = "No Results" }

[keybinds]
quick_activate = []

[providers]
default = [
  "desktopapplications",
  "menus",
]

[[providers.prefixes]]
prefix = "/"
provider = "providerlist"

[[providers.prefixes]]
prefix = "."
provider = "files"

[[providers.prefixes]]
prefix = ":"
provider = "symbols"

[[providers.prefixes]]
prefix = "="
provider = "calc"

[[providers.prefixes]]
prefix = "$"
provider = "clipboard"
